### ISSUE TITLE
May 2020 Melodic Release

### ISSUE THREAD

**Issue by tylerjw** [ros-planning/moveit_msgs#71]
I copied this from what I put in the [moveit release issue](https://github.com/ros-planning/moveit/issues/2066).  I don't think we need nearly as much time to push this out and I'm unsure if all these steps are necessary.  Please let me know if we can drop any of them.  I would like to push this out quickly though because jog_arm depends on the changes I just got back-ported here.

## Timeline
1. May 7 - Create Issue to decide on issues
1. May 10 - Issues picked and PR(s) for backports created (jog_arm and other fixes)
1. May 11 - Backport PR(s) merged, Code freeze of melodic-devel
1. May 13 - Create shadow repo for testing and post on discord
1. May 15 -  Run bloom

## Backport Discussion
Here are the changes in master that are not in melodic-devel and the one I merged.  LMK if any of these should be backported, and if I'm missing any that are merged but not yet in a release so we can put them in the release notes.  Anything that changes API of an existing message is struck out.

### Back-Ported Changes
 - [x] Add messages to plan for sequences (#65): https://github.com/ros-planning/moveit_msgs/pull/74
 - [x] bump cmake version (#67)
 - [x] Change jogging drift dimensions (#63)
 - [x] Add ChangeControlDimensions.srv for moveit_jog_arm (#61)

### Message API Changing Changes
~~Add origin Pose to CollisionObject (#69)~~
~~Add field quality to PlaceLocation (#64)~~
~~Extend MotionPlanRequest with seed trajectories (#46)~~
~~Ability to hide visualized robot states (#55)~~

### Next release candidates (changes made for PR not yet merged in moveit)
~~Add service to update pointcloud octomap (#66)~~

## Tasks (with owners)
 - [x] Create an issue to track release - @tylerjw 
 - [x] Plan the possible date - @tylerjw
 - [x] Revert subframes change from melodic-devel - @rhaschke / @v4hn 
 - [x] Decide on what will be backported - @rhaschke / @v4hn  
 - [x] Create backport PRs - @tylerjw 
 - [x] Merge backport PRs - @rhaschke / @v4hn 
 - [x] Notify release section of discourse - @JafarAbdi 
 - [x] Run buildfarm tests - @JafarAbdi 
 - [x] Update changelogs - @mlautman 
 - [ ] Create tag with version number - @mlautman 
 - [x] Update versions in package.xml - @mlautman 
 - [ ] Run bloom - @mlautman 
 - [ ] Publish release notes on moveit.ros.org - @mlautman 
 - [ ] Post to MoveIt Discourse - @mlautman 

## Updates
* Update: Struck out anything that changes an existing message API
* #66 moved to next release candidates

**Comment by rhaschke** [comment]
We just need to prepare a new release... 
Looking at the diffs since the last release, I'm wondering why we have the subframes support in moveit_msgs, but MoveIt's melodic branch isn't supporting that. I think, we should remove the sub_frames support here before releasing into Melodic.

**Comment by v4hn** [comment]
> Looking at the diffs since the last release, I'm wondering why we have the subframes support in moveit_msgs,
> but MoveIt's melodic branch isn't supporting that.

That was pointed out a number of times. During backporting I also explicitly stated that I left this feature out,
because it is distributed over quite a number of commits and was still buggy.
Actually, I still think it's buggy until we change the frame semantics for world object frames with Felix's wip change...

> I think, we should remove the sub_frames support here before releasing into Melodic.

If this change was really not released previously (I thought so) and is the only change to the message, I fully agree!

**Comment by v4hn** [comment]
Apparently this change was really never released in melodic and I would veto to remove it there.

**Comment by felixvd** [comment]
IIRC the subframes feature was merged only into `master` and not `melodic-devel` because moveit_msgs shouldn't change after release. Am I missing something?

**Comment by v4hn** [comment]
Am I missing something?
Yes, the fact that [the message change was indeed merged in `melodic-devel`](https://github.com/ros-planning/moveit_msgs/pull/50) a year ago, although the code support was never added to the main moveit repo.

**Comment by felixvd** [comment]
Right. I never changed the target of that PR to master. Splitting the code across multiple repositories has its pitfalls :0

I have no problem with reverting it in melodic-devel and keeping the feature in master/noetic as planned.

**Comment by tylerjw** [comment]
I updated the list of potential backports to include only those that add new messages and not ones that change existing messages.  Please advise on which ones I should prepare a backport for?

**Comment by v4hn** [comment]
- Add service to update pointcloud octomap (#66)

The corresponding support in https://github.com/ros-planning/moveit/pull/1984 is not merged yet, so no need to backport (yet?)

- Add messages to plan for sequences (#65)

@jschleicher do you want to see these messages in melodic-devel too?
I don't think there is harm in having them and even your standalone repository could use them.

- bump cmake version (#67)

This version is supported since kinetic, so this should be backported.

**Comment by ct2034** [comment]
Yes, we need the messages in melodic-devel.

**Comment by tylerjw** [comment]
@JafarAbdi It is now your turn to do the next steps.  See Making a new release section of https://moveit.ros.org/documentation/contributing/pullrequests/

**Comment by tylerjw** [comment]
@JafarAbdi Prepared the release notes and a version bump: https://github.com/ros-planning/moveit_msgs/pull/77

**Comment by rhaschke** [comment]
Release PR: ros/rosdistro#24992

**Comment by tylerjw** [comment]
@rhaschke your PR to rosdistro got merged.  What are the remaining steps?  I'm not sure I have the right list of steps in the description for this.

**Comment by rhaschke** [comment]
We can already use the newly released package in all builds referring to the testing repos, i.e. `ros-shadow-fixed` in Travis configs. If the next sync happened, the package will be available in the default repo as well. This can be checked here:
http://repositories.ros.org/status_page/ros_melodic_default.html?q=moveit_msgs
